# Generated by Django 3.2.13 on 2022-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteCust',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('deletecust', models.IntegerField(default=None, null=True, verbose_name='')),
                ('deletecon', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
    ]
