# Generated by Django 3.2.13 on 2022-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0002_deletecust'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='date',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
    ]
