# Generated by Django 3.2.13 on 2022-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0003_customerinfo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='Cust ID.')),
                ('appdate', models.DateField(blank=True, null=True)),
                ('apptime', models.CharField(blank=True, max_length=5, verbose_name='')),
                ('appdescrip', models.CharField(blank=True, max_length=1000, verbose_name='')),
            ],
        ),
    ]
