# Generated by Django 3.2.13 on 2022-05-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='conid',
        ),
    ]
