# Generated by Django 3.2.13 on 2022-05-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0005_remove_customerinfo_conid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerinfo',
            unique_together={('custfirstname', 'custlastname', 'custadd1', 'custcity', 'custst')},
        ),
    ]
