# Generated by Django 3.2.13 on 2022-05-05 19:54

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0008_alter_customerinfo_custadd2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='custcell1',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Cell Phone #1:'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='custcell2',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Cell Phone #2:'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='custemail1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email #1:'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='custemail2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email #2:'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='custhome',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Home Phone:'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='custwork1',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Work Phone #1:'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='custwork2',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Work Phone #2:'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name=''),
        ),
    ]
