# Generated by Django 3.2.13 on 2022-05-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0009_auto_20220505_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='custcompanytname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Name:'),
        ),
    ]
