# Generated by Django 3.2.13 on 2022-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0011_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='callindate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
