# Generated by Django 3.2.13 on 2022-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0012_appointment_callindate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('appointmenttime', models.CharField(blank=True, max_length=10, unique=True, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apptime',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
