# Generated by Django 3.2.13 on 2022-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0016_alter_appointment_apptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppQueue',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='Cust ID.')),
                ('appdate', models.DateField(blank=True, null=True)),
                ('apptime', models.IntegerField(default=None, null=True, verbose_name='Cust ID.')),
                ('appdescrip', models.CharField(blank=True, max_length=1000, verbose_name='')),
                ('callindate', models.DateField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='')),
            ],
        ),
    ]
