# Generated by Django 3.2.13 on 2022-05-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0017_appqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppQueueCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=None, null=True, verbose_name='Cust ID.')),
            ],
        ),
    ]
