# Generated by Django 3.2.13 on 2022-05-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0018_appqueuecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mainid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
