# Generated by Django 3.2.13 on 2022-05-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0020_alter_appqueuecount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apptime',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apptime', to='absdatabase.time', to_field='appointmenttime', verbose_name=''),
        ),
    ]
