# Generated by Django 3.2.13 on 2022-05-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0023_auto_20220511_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='bidid',
            field=models.IntegerField(default=None, null=True, verbose_name='Bid ID.'),
        ),
    ]
