# Generated by Django 3.2.13 on 2022-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0024_bidpage_bidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='beamlength1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamsize1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamsize2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamsize3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamtype1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='ceilingheight1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='ceilingheight2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='footingqty',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='footingsize',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lclength1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lclength2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lclength3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcqty1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcqty2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcqty3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lctransition1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lctransition2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lctransition3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscdescription1',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscdescription2',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscdescription3',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscdescription4',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='misclabor1',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='misclabor2',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='misclabor3',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='misclabor4',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscqty1',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscqty2',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscqty3',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscqty4',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='qty1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='qty2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='qty3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
