# Generated by Django 3.2.13 on 2022-05-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0028_auto_20220512_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidpage',
            name='ceilingheight1',
        ),
    ]
