# Generated by Django 3.2.13 on 2022-05-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0029_remove_bidpage_ceilingheight1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidpage',
            name='ceilingheight2',
        ),
    ]
