# Generated by Django 3.2.13 on 2022-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0032_auto_20220512_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heightft',
            name='feet',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='heightin',
            name='inches',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Increase'),
        ),
    ]
