# Generated by Django 3.2.13 on 2022-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0033_auto_20220512_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('beamsize', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Increase')),
                ('beamcost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Increase')),
            ],
        ),
        migrations.CreateModel(
            name='Qty',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Increase')),
            ],
        ),
    ]
