# Generated by Django 3.2.13 on 2022-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0034_beam_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeamFt',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('feet', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='BeamIn',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('inches', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='beam',
            name='beamcost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='beam',
            name='beamsize',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='heightin',
            name='inches',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='qty',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=''),
        ),
    ]
