# Generated by Django 3.2.13 on 2022-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0035_auto_20220512_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam',
            name='beamcost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='beam',
            name='beamsize',
            field=models.CharField(blank=True, max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='beamin',
            name='inches',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='heightin',
            name='inches',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='qty',
            name='quantity',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
