# Generated by Django 3.2.13 on 2022-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0036_auto_20220512_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeamInfo',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('beam_type', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('beam_size', models.CharField(blank=True, max_length=20, unique=True, verbose_name='')),
                ('beam_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('beam_labor', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='GluLamBeam',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('beam_type', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('beam_size', models.CharField(blank=True, max_length=20, unique=True, verbose_name='')),
                ('beam_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('beam_labor', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='LallyColumn',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('lally_size', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('lally_return', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('lally_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='LallyColumnReturn',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('lally_return', models.CharField(blank=True, max_length=20, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='LVLBeam',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('beam_type', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('beam_size', models.CharField(blank=True, max_length=20, unique=True, verbose_name='')),
                ('beam_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('beam_labor', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='SteelBeam',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('beam_type', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('beam_size', models.CharField(blank=True, max_length=20, unique=True, verbose_name='')),
                ('beam_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('beam_labor', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='beamtype',
            name='beam_type',
            field=models.CharField(blank=True, max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamtype1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
