# Generated by Django 3.2.13 on 2022-05-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0037_auto_20220513_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamtype1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beam_type1', to='absdatabase.beamtype', verbose_name=''),
        ),
    ]
