# Generated by Django 3.2.13 on 2022-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0038_alter_bidpage_beamtype1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamtype1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
