# Generated by Django 3.2.13 on 2022-05-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0041_delete_beamtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='qty1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row1qty', to='absdatabase.qty', verbose_name=''),
        ),
    ]
