# Generated by Django 3.2.13 on 2022-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0042_alter_bidpage_qty1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='beamlength1ft',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength1in',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
