# Generated by Django 3.2.13 on 2022-05-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0043_auto_20220514_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidpage',
            name='beamlength1',
        ),
    ]
