# Generated by Django 3.2.13 on 2022-05-14 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0044_remove_bidpage_beamlength1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength1ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength1ft', to='absdatabase.heightft', verbose_name=''),
        ),
    ]
