# Generated by Django 3.2.13 on 2022-05-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0045_alter_bidpage_beamlength1ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength1in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength1in', to='absdatabase.heightin', verbose_name=''),
        ),
    ]
