# Generated by Django 3.2.13 on 2022-05-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0046_alter_bidpage_beamlength1in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='lclength1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength1', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty1', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lctransition1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition1', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
    ]
