# Generated by Django 3.2.13 on 2022-05-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0047_auto_20220514_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='beamlength2ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength2ft', to='absdatabase.heightft', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength2in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength2in', to='absdatabase.heightin', verbose_name=''),
        ),
    ]
