# Generated by Django 3.2.13 on 2022-05-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0048_auto_20220515_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2ft', to='absdatabase.heightft', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2in', to='absdatabase.heightin', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2qty', to='absdatabase.qty', verbose_name=''),
        ),
    ]
