# Generated by Django 3.2.13 on 2022-05-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0052_auto_20220515_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='beamlength3ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3ft', to='absdatabase.heightft', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength3in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3in', to='absdatabase.heightin', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength4ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4ft', to='absdatabase.heightft', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength4in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4in', to='absdatabase.heightin', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength5ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5ft', to='absdatabase.heightft', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength5in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5in', to='absdatabase.heightin', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength6ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row6ft', to='absdatabase.heightft', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamlength6in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row6in', to='absdatabase.heightin', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lclength3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength3', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lclength4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength4', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lclength5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength5', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lclength6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength6', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcqty3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty3', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcqty4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty4', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcqty5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty5', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcqty6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty6', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lctransition3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition3', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lctransition4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition4', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lctransition5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition5', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lctransition6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition6', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='qty3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3qty', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='qty4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4qty', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='qty5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5qty', to='absdatabase.qty', verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='qty6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row6qty', to='absdatabase.qty', verbose_name=''),
        ),
    ]
