# Generated by Django 3.2.13 on 2022-05-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0053_auto_20220515_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='footingqty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footingqty', to='absdatabase.qty', verbose_name=''),
        ),
    ]
