# Generated by Django 3.2.13 on 2022-05-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0055_footingsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='footingsize',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footingsize', to='absdatabase.footingsize', verbose_name=''),
        ),
    ]
