# Generated by Django 3.2.13 on 2022-05-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0056_alter_bidpage_footingsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='footingsize',
            name='footing_cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='footingsize',
            name='footing_labor',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
