# Generated by Django 3.2.13 on 2022-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0057_auto_20220516_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='miscmat1',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscmat2',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscmat3',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscmat4',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
