# Generated by Django 3.2.13 on 2022-05-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0059_auto_20220516_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamft',
            name='feet',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='beamin',
            name='inches',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength1ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength1ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength1in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength1in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength3ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength3in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength4ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength4in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength5ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength5in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength6ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row6ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength6in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row6in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength1', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength2', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength3', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength4', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength5', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength6', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty1', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty2', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty3', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty4', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty5', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty6', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row1qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row6qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='heightft',
            name='feet',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='heightin',
            name='inches',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='lallycolumn',
            name='lally_size',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='lallycolumnreturn',
            name='lally_return',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='qty',
            name='quantity',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name=''),
        ),
    ]
