# Generated by Django 3.2.13 on 2022-05-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0060_auto_20220516_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength2ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength2in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength3ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength3ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength3in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength3in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength4ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength4ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength4in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength4in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength5ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength5ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength5in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength5in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength6ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength6ft', to='absdatabase.heightft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength6in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength6in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
    ]
