# Generated by Django 3.2.13 on 2022-05-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0061_auto_20220516_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength1ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength1ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength2ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength3ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength3ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength4ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength4ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength5ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength5ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength6ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength6ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
    ]
