# Generated by Django 3.2.13 on 2022-05-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0062_auto_20220516_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='beamcost1',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcost1',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
