# Generated by Django 3.2.13 on 2022-05-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0063_auto_20220516_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamcost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
    ]
