# Generated by Django 3.2.13 on 2022-05-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0064_auto_20220516_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='beamcost2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamcost3',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamcost4',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamcost5',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='beamcost6',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lallycost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lallycost2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lallycost3',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lallycost4',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lallycost5',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lallycost6',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcost2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcost3',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcost4',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcost5',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='lcost6',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name=''),
        ),
    ]
