# Generated by Django 3.2.13 on 2022-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0065_auto_20220516_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCost',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('beamcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('beamlaborcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('beamlallycost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('miscmaterialcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('misclaborcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('totalmaterialcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('taxcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('totalcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('increase', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('grandtotalcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
            ],
        ),
    ]
