# Generated by Django 3.2.13 on 2022-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0066_jobcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='jobid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
