# Generated by Django 3.2.13 on 2022-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0067_jobcost_jobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='custid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
