# Generated by Django 3.2.13 on 2022-05-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0068_jobcost_custid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcost',
            old_name='beamcost',
            new_name='laborcost',
        ),
        migrations.RenameField(
            model_name='jobcost',
            old_name='beamlaborcost',
            new_name='materialcost',
        ),
        migrations.RemoveField(
            model_name='jobcost',
            name='beamlallycost',
        ),
        migrations.RemoveField(
            model_name='jobcost',
            name='misclaborcost',
        ),
        migrations.RemoveField(
            model_name='jobcost',
            name='miscmaterialcost',
        ),
    ]
