# Generated by Django 3.2.13 on 2022-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0069_auto_20220516_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='footinglabor',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='footingmat',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
