# Generated by Django 3.2.13 on 2022-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0070_auto_20220516_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcost',
            old_name='jobid',
            new_name='bidid',
        ),
        migrations.AlterField(
            model_name='beaminfo',
            name='beam_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='beaminfo',
            name='beam_labor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamcost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamcost2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamcost3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamcost4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamcost5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamcost6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='footinglabor',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='footingmat',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lallycost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lallycost2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lallycost3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lallycost4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lallycost5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lallycost6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcost2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcost3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcost4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcost5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcost6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='misclabor1',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='misclabor2',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='misclabor3',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='misclabor4',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscmat1',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscmat2',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscmat3',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscmat4',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='grandtotalcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='increase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='laborcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='materialcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='taxcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='totalcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='totalmaterialcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
    ]
