# Generated by Django 3.2.13 on 2022-05-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0071_auto_20220516_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcost',
            old_name='totalmaterialcost',
            new_name='totalmatcost',
        ),
    ]
