# Generated by Django 3.2.13 on 2022-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0073_jobcost_prodqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('tax', models.CharField(blank=True, max_length=50, verbose_name='Tax Rate')),
                ('taxperc', models.CharField(blank=True, max_length=50, verbose_name='')),
            ],
        ),
    ]
