# Generated by Django 3.2.13 on 2022-05-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0076_alter_taxrate_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='taxrate',
            field=models.ForeignKey(blank=True, default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxrate', to='absdatabase.taxrate', to_field='tax', verbose_name=''),
        ),
    ]
