# Generated by Django 3.2.13 on 2022-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0077_alter_jobcost_taxrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7, unique=True, verbose_name=''),
        ),
    ]
