# Generated by Django 3.2.13 on 2022-05-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0080_alter_jobcost_taxrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcost',
            name='taxcost',
        ),
        migrations.RemoveField(
            model_name='jobcost',
            name='taxrate',
        ),
    ]
