# Generated by Django 3.2.13 on 2022-05-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0085_auto_20220518_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamsize1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamtype1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
