# Generated by Django 3.2.13 on 2022-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0090_bidpage_beamselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamsize1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
    ]
