# Generated by Django 3.2.13 on 2022-05-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0091_alter_bidpage_beamsize1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lallycolumn',
            name='lally_size',
            field=models.CharField(blank=True, max_length=20, verbose_name=''),
        ),
    ]
