# Generated by Django 3.2.13 on 2022-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0094_auto_20220601_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='misclabor1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscmat1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
    ]
