# Generated by Django 3.2.13 on 2022-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0095_auto_20220602_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='misclabor2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='misclabor3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='misclabor4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscmat2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscmat3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscmat4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
    ]
