# Generated by Django 3.2.13 on 2022-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0096_auto_20220602_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='misccost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='misccost2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='misccost3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='misccost4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
    ]
