# Generated by Django 3.2.13 on 2022-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0097_auto_20220602_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidpage',
            old_name='misccost1',
            new_name='misclaborcost1',
        ),
        migrations.RenameField(
            model_name='bidpage',
            old_name='misccost2',
            new_name='misclaborcost2',
        ),
        migrations.RenameField(
            model_name='bidpage',
            old_name='misccost3',
            new_name='misclaborcost3',
        ),
        migrations.RenameField(
            model_name='bidpage',
            old_name='misccost4',
            new_name='misclaborcost4',
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscmatcost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscmatcost2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscmatcost3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidpage',
            name='miscmatcost4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name=''),
        ),
    ]
