# Generated by Django 3.2.13 on 2022-06-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0099_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='downpayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='finalpayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
    ]
