# Generated by Django 3.2.13 on 2022-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0100_auto_20220604_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownPayTerms',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('terms', models.CharField(blank=True, max_length=150, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='FinalPayTerms',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('terms', models.CharField(blank=True, max_length=150, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='downpayamount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='downpaydescr',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='finalpayamount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='finalpaydescr',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='workorderdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
