# Generated by Django 3.2.13 on 2022-06-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0101_auto_20220605_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='downpaydescr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo1', to='absdatabase.downpayterms', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='finalpaydescr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo1', to='absdatabase.finalpayterms', verbose_name=''),
        ),
    ]
