# Generated by Django 3.2.13 on 2022-06-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0102_auto_20220605_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='downpayamount',
            new_name='payment1',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='downpaydescr',
            new_name='term1',
        ),
    ]
