# Generated by Django 3.2.13 on 2022-06-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0103_auto_20220605_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment1date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment2',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment2date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment3',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment3date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='term2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term2', to='absdatabase.downpayterms', verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='term3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term3', to='absdatabase.downpayterms', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='term1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term1', to='absdatabase.downpayterms', verbose_name=''),
        ),
    ]
