# Generated by Django 3.2.13 on 2022-06-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0105_auto_20220605_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='finalpaydescr',
        ),
    ]
