# Generated by Django 3.2.13 on 2022-06-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0106_remove_contract_finalpaydescr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcost',
            name='downpayment',
        ),
        migrations.RemoveField(
            model_name='jobcost',
            name='finalpayment',
        ),
    ]
