# Generated by Django 3.2.13 on 2022-06-06 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0107_auto_20220605_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='payment1',
            new_name='deposit',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='payment1date',
            new_name='depositdate',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='term1',
            new_name='depositterms',
        ),
    ]
