# Generated by Django 3.2.13 on 2022-06-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0108_auto_20220605_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='finalpayamount',
            new_name='finalpayment',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='finalpaydate',
            new_name='finalpaymentdate',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='termfinal',
            new_name='termsfinal',
        ),
    ]
