# Generated by Django 3.2.13 on 2022-06-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0110_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='depositperc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depositperc', to='absdatabase.percentage', to_field='multiplier', verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='pay2perc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay2perc', to='absdatabase.percentage', to_field='multiplier', verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='pay3perc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay3perc', to='absdatabase.percentage', to_field='multiplier', verbose_name=''),
        ),
    ]
