# Generated by Django 3.2.13 on 2022-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0111_auto_20220606_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='customdeposit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='seconddeposit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='thirddeposit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
