# Generated by Django 3.2.13 on 2022-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0112_auto_20220606_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
