# Generated by Django 3.2.13 on 2022-06-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0113_customerinfo_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='Cust ID.')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='photos',
        ),
    ]
