# Generated by Django 3.2.13 on 2022-06-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0118_alter_photo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='jobphotos',
        ),
    ]
