# Generated by Django 3.2.13 on 2022-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0121_alter_photo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='Cust ID.')),
                ('pdfs', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
            options={
                'db_table': 'jobpdf',
            },
        ),
    ]
