# Generated by Django 3.2.13 on 2022-06-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0122_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdfs',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
