# Generated by Django 3.2.13 on 2022-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0123_alter_pdf_pdfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdfs',
            field=models.ImageField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
