# Generated by Django 3.2.13 on 2022-06-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0125_auto_20220610_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='worktype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktype1', to='absdatabase.worktype', verbose_name=''),
        ),
    ]
