# Generated by Django 3.2.13 on 2022-06-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0126_alter_bidpage_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='type',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name=''),
        ),
    ]
