# Generated by Django 3.2.13 on 2022-06-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0127_alter_worktype_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
    ]
