# Generated by Django 3.2.13 on 2022-06-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0128_alter_photo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pdf',
            table=None,
        ),
    ]
