# Generated by Django 3.2.13 on 2022-06-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0129_alter_pdf_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty1',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty1', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
    ]
