# Generated by Django 3.2.13 on 2022-06-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0131_auto_20220611_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength2ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength2in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength2in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength3ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength3ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength3in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength3in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength4ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength4ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength4in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength4in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength5ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength5ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength5in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength5in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength6ft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength6ft', to='absdatabase.beamft', to_field='feet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='beamlength6in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamlength6in', to='absdatabase.heightin', to_field='inches', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='chfeet1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chfeet1', to='absdatabase.heightft', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='chinches1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chinches1', to='absdatabase.heightin', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='footingqty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footingqty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='footingsize',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footingsize', to='absdatabase.footingsize', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength2', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength3', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength4', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength5', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lclength6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength6', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty2', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty3', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty4', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty5', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty6', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lctransition2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition2', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lctransition3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition3', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lctransition4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition4', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lctransition5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition5', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lctransition6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition6', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscqty1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscqty1', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscqty2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscqty2', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscqty3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscqty3', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='miscqty4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscqty4', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row2qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row3qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row4qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row5qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='qty6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='row6qty', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
    ]
