# Generated by Django 3.2.13 on 2022-06-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0134_auto_20220611_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpage',
            name='lclength1',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lclength1', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lcqty1',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcqty1', to='absdatabase.qty', to_field='quantity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidpage',
            name='lctransition1',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lctransition1', to='absdatabase.lallycolumnreturn', verbose_name=''),
        ),
    ]
