# Generated by Django 3.2.13 on 2022-06-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absdatabase', '0136_auto_20220611_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpage',
            name='disabled',
            field=models.IntegerField(default=0.0, null=True, verbose_name=''),
        ),
    ]
