from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = "absdatabase"
urlpatterns = [
    path('abs/', LoginView.as_view(template_name='abs/welcome.html'), name='abs'),
    path('<int:id>/main/', views.main, name='main'),
    path('abs/', views.welcome, name='abs'),
    path('preappoint/', views.preappoint, name='preappoint'),
    path('newcust/', views.newcust, name='newcust'),
    path('custerror/', views.custerror, name='custerror'),
    path('<int:id>/deletecust2/', views.deletecust2, name='deletecust2'),
    path('<int:id>/deletecust4/', views.deletecust4, name='deletecust4'),
    path('cust_info_existing', views.cust_info_existing, name='cust_info_existing'),

    path('<int:id>/custinfo/', views.custinfo, name='custinfo'),


    path('<int:custid>/photo/', views.photo, name='photo'),
    path('<int:custid>/PDF1/', views.PDF1, name='PDF1'),
    path('<int:custid>/gallery/', views.gallery, name='gallery'),
    path('<int:custid>/gallery2/', views.gallery2, name='gallery2'),
    path('<int:custid>/PDFgallery/', views.PDFgallery, name='PDFgallery'),
    path('<int:custid>/PDFgallery2/', views.PDFgallery2, name='PDFgallery2'),



    path('<int:id>/deletecust/', views.deletecust, name='deletecust'),
    path('<int:id>/edit_cust_info/', views.edit_cust_info, name='edit_cust_info'),
    path('<int:custid>/appointment/', views.appointment, name='appointment'),
    path('<int:custid>/appointmentdate/', views.appointmentdate, name='appointmentdate'),
    path('<int:custid>/time/', views.time, name='time'),
    path('<int:custid>/scopeofwork/', views.scopeofwork, name='scopeofwork'),
    path('appqueue/', views.appqueue, name='appqueue'),
    path('<int:custid>/appendapp/', views.appendapp, name='appendapp'),
    path('<int:custid>/scheduledappt/', views.scheduledappt, name='scheduledappt'),
    path('<int:id>/worktype/', views.worktype, name='worktype'),
    path('<int:id>/bidpage/', views.bidpage, name='bidpage'),
    path('<int:id>/beamtype/', views.beamtype, name='beamtype'),
    path('<int:id>/beamreset/', views.beamreset, name='beamreset'),

    path('<int:id>/ajax/load_beamselect/', views.load_beamselect, name='ajax_load_beamselect'),
    path('<int:id>/ajax/load_beamtype/', views.load_beamtype, name='ajax_load_beamtype'),
    path('<int:id>/ajax/load_beamtypeB/', views.load_beamtypeB, name='ajax_load_beamtypeB'),
    path('<int:id>/ajax/load_beaminfo/', views.load_beaminfo, name='ajax_load_beaminfo'),
    path('<int:id>/ajax/load_beamsize/', views.load_beamsize, name='ajax_load_beamsize'),
    path('<int:id>/beamsize/', views.beamsize, name='beamsize'),
    path('<int:id>/chfeet/', views.chfeet, name='chfeet'),
    path('<int:id>/chinches/', views.chinches, name='chinches'),
    path('<int:id>/ajax/load_disable/', views.load_disable, name='ajax_load_disable'),

    path('<int:id>/qty1/', views.qty1, name='qty1'),
    path('<int:id>/qty1A/', views.qty1A, name='qty1A'),
    path('<int:id>/load_qty1/', views.load_qty1, name='load_qty1'),
    path('<int:id>/ajax/load_ft1_0/', views.load_ft1_0, name='ajax_load_ft1_0'),

    path('<int:id>/ft1/', views.ft1, name='ft1'),
    path('<int:id>/inch1/', views.inch1, name='inch1'),
    path('<int:id>/ajax/load_in1_0/', views.load_in1_0, name='ajax_load_in1_0'),
    path('<int:id>/lcqty1/', views.lcqty1, name='lcqty1'),
    path('<int:id>/lclenght1/', views.lclenght1, name='lclenght1'),
    path('<int:id>/ajax/load_lclenght1_0/', views.load_lclenght1_0, name='ajax_load_lclenght1_0'),
    path('<int:id>/lctransition1/', views.lctransition1, name='lctransition1'),
    path('<int:id>/ajax/load_lctransition1_0/', views.load_lctransition1_0, name='ajax_load_lctransition1_0'),


    path('<int:id>/qty2/', views.qty2, name='qty2'),
    path('<int:id>/qty2A/', views.qty2A, name='qty2A'),
    path('<int:id>/load_qty2/', views.load_qty2, name='load_qty2'),
    path('<int:id>/ajax/load_ft2_0/', views.load_ft2_0, name='ajax_load_ft2_0'),
    path('<int:id>/ajax/load_in2_0/', views.load_in2_0, name='ajax_load_in2_0'),
    path('<int:id>/ft2/', views.ft2, name='ft2'),
    path('<int:id>/inch2/', views.inch2, name='inch2'),
    path('<int:id>/lcqty2/', views.lcqty2, name='lcqty2'),
    path('<int:id>/lclenght2/', views.lclenght2, name='lclenght2'),
    path('<int:id>/lctransition2/', views.lctransition2, name='lctransition2'),
    path('<int:id>/ajax/load_lclenght2_0/', views.load_lclenght2_0, name='ajax_load_lclenght2_0'),
    path('<int:id>/ajax/load_lctransition2_0/', views.load_lctransition2_0, name='ajax_load_lctransition2_0'),

    path('<int:id>/qty3/', views.qty3, name='qty3'),
    path('<int:id>/qty3A/', views.qty3A, name='qty3A'),
    path('<int:id>/load_qty3/', views.load_qty3, name='load_qty3'),
    path('<int:id>/ajax/load_ft3_0/', views.load_ft3_0, name='ajax_load_ft3_0'),
    path('<int:id>/ajax/load_in3_0/', views.load_in3_0, name='ajax_load_in3_0'),
    path('<int:id>/ft3/', views.ft3, name='ft3'),
    path('<int:id>/inch3/', views.inch3, name='inch3'),
    path('<int:id>/lcqty3/', views.lcqty3, name='lcqty3'),
    path('<int:id>/lcqty3A/', views.lcqty3A, name='lcqty3A'),
    path('<int:id>/lclenght3/', views.lclenght3, name='lclenght3'),
    path('<int:id>/lctransition3/', views.lctransition3, name='lctransition3'),
    path('<int:id>/ajax/load_lclenght3_0/', views.load_lclenght3_0, name='ajax_load_lclenght3_0'),
    path('<int:id>/ajax/load_lctransition3_0/', views.load_lctransition3_0, name='ajax_load_lctransition3_0'),

    path('<int:id>/qty4/', views.qty4, name='qty4'),
    path('<int:id>/qty4A/', views.qty4A, name='qty4A'),
    path('<int:id>/load_qty4/', views.load_qty4, name='load_qty4'),
    path('<int:id>/ajax/load_ft4_0/', views.load_ft4_0, name='ajax_load_ft4_0'),
    path('<int:id>/ajax/load_in4_0/', views.load_in4_0, name='ajax_load_in4_0'),
    path('<int:id>/ft4/', views.ft4, name='ft4'),
    path('<int:id>/inch4/', views.inch4, name='inch4'),
    path('<int:id>/lcqty4/', views.lcqty4, name='lcqty4'),
    path('<int:id>/lclenght4/', views.lclenght4, name='lclenght4'),
    path('<int:id>/lctransition4/', views.lctransition4, name='lctransition4'),
    path('<int:id>/ajax/load_lclenght4_0/', views.load_lclenght4_0, name='ajax_load_lclenght4_0'),
    path('<int:id>/ajax/load_lctransition4_0/', views.load_lctransition4_0, name='ajax_load_lctransition4_0'),

    path('<int:id>/qty5/', views.qty5, name='qty5'),
    path('<int:id>/qty5A/', views.qty5A, name='qty5A'),
    path('<int:id>/load_qty5/', views.load_qty5, name='load_qty5'),
    path('<int:id>/ajax/load_ft5_0/', views.load_ft5_0, name='ajax_load_ft5_0'),
    path('<int:id>/ajax/load_in5_0/', views.load_in5_0, name='ajax_load_in5_0'),
    path('<int:id>/ft5/', views.ft5, name='ft5'),
    path('<int:id>/inch5/', views.inch5, name='inch5'),
    path('<int:id>/lcqty5/', views.lcqty5, name='lcqty5'),
    path('<int:id>/lclenght5/', views.lclenght5, name='lclenght5'),
    path('<int:id>/lctransition5/', views.lctransition5, name='lctransition5'),
    path('<int:id>/ajax/load_lclenght5_0/', views.load_lclenght5_0, name='ajax_load_lclenght5_0'),
    path('<int:id>/ajax/load_lctransition5_0/', views.load_lctransition5_0, name='ajax_load_lctransition5_0'),

    path('<int:id>/qty6/', views.qty6, name='qty6'),
    path('<int:id>/qty6A/', views.qty6A, name='qty6A'),
    path('<int:id>/load_qty6/', views.load_qty6, name='load_qty6'),
    path('<int:id>/ajax/load_ft6_0/', views.load_ft6_0, name='ajax_load_ft6_0'),
    path('<int:id>/ajax/load_in6_0/', views.load_in6_0, name='ajax_load_in6_0'),
    path('<int:id>/ft6/', views.ft6, name='ft6'),
    path('<int:id>/inch6/', views.inch6, name='inch6'),
    path('<int:id>/lcqty6/', views.lcqty6, name='lcqty6'),
    path('<int:id>/lclenght6/', views.lclenght6, name='lclenght6'),
    path('<int:id>/lctransition6/', views.lctransition6, name='lctransition6'),
    path('<int:id>/ajax/load_lclenght6_0/', views.load_lclenght6_0, name='ajax_load_lclenght6_0'),
    path('<int:id>/ajax/load_lctransition6_0/', views.load_lctransition6_0, name='ajax_load_lctransition6_0'),
    path('<int:id>/jobcost/', views.jobcost, name='jobcost'),
    path('<int:id>/increase/', views.increase, name='increase'),
    path('<int:id>/totals/', views.totals, name='totals'),
    path('<int:id>/totals2/', views.totals2, name='totals2'),
    path('<int:id>/totals3/', views.totals3, name='totals3'),
    path('<int:id>/totals4/', views.totals4, name='totals4'),
    path('<int:id>/totals5/', views.totals5, name='totals5'),
    path('<int:id>/totals6/', views.totals6, name='totals6'),
    path('<int:id>/load_materialcost/', views.load_materialcost, name='load_materialcost'),
    path('<int:id>/footingqty/', views.footingqty, name='footingqty'),
    path('<int:id>/footingsize/', views.footingsize, name='footingsize'),
    path('<int:id>/ajax/load_footingsize_0/', views.load_footingsize_0, name='load_footingsize_0'),
    path('<int:id>/totalsfootingsize/', views.totalsfootingsize, name='totalsfootingsize'),
    path('<int:id>/misc1qty/', views.misc1qty, name='misc1qty'),
    path('<int:id>/misc1descrip/', views.misc1descrip, name='misc1descrip'),
    path('<int:id>/misc1mat/', views.misc1mat, name='misc1mat'),
    path('<int:id>/misc1labor/', views.misc1labor, name='misc1labor'),
    path('<int:id>/misctotal/', views.misctotal, name='misctotal'),
    path('<int:id>/ajax/load_misc1descrip_0/', views.load_misc1descrip_0, name='load_misc1descrip_0'),
    path('<int:id>/ajax/load_misc1mat_0/', views.load_misc1mat_0, name='load_misc1mat_0'),
    path('<int:id>/ajax/load_misc1labor_0/', views.load_misc1labor_0, name='load_misc1labor_0'),

    path('<int:id>/misc2qty/', views.misc2qty, name='misc2qty'),
    path('<int:id>/misc2descrip/', views.misc2descrip, name='misc2descrip'),
    path('<int:id>/misc2mat/', views.misc2mat, name='misc2mat'),
    path('<int:id>/misc2labor/', views.misc2labor, name='misc2labor'),
    path('<int:id>/ajax/load_misc2descrip_0/', views.load_misc2descrip_0, name='load_misc2descrip_0'),
    path('<int:id>/ajax/load_misc2mat_0/', views.load_misc2mat_0, name='load_misc2mat_0'),
    path('<int:id>/ajax/load_misc2labor_0/', views.load_misc2labor_0, name='load_misc2labor_0'),

    path('<int:id>/misc3qty/', views.misc3qty, name='misc3qty'),
    path('<int:id>/misc3descrip/', views.misc3descrip, name='misc3descrip'),
    path('<int:id>/misc3mat/', views.misc3mat, name='misc3mat'),
    path('<int:id>/misc3labor/', views.misc3labor, name='misc3labor'),
    path('<int:id>/ajax/load_misc3descrip_0/', views.load_misc3descrip_0, name='load_misc3descrip_0'),
    path('<int:id>/ajax/load_misc3mat_0/', views.load_misc3mat_0, name='load_misc3mat_0'),
    path('<int:id>/ajax/load_misc3labor_0/', views.load_misc3labor_0, name='load_misc3labor_0'),

    path('<int:id>/misc4qty/', views.misc4qty, name='misc4qty'),
    path('<int:id>/misc4descrip/', views.misc4descrip, name='misc4descrip'),
    path('<int:id>/misc4mat/', views.misc4mat, name='misc4mat'),
    path('<int:id>/misc4labor/', views.misc4labor, name='misc4labor'),
    path('<int:id>/ajax/load_misc4descrip_0/', views.load_misc4descrip_0, name='load_misc4descrip_0'),
    path('<int:id>/ajax/load_misc4mat_0/', views.load_misc4mat_0, name='load_misc4mat_0'),
    path('<int:id>/ajax/load_misc4labor_0/', views.load_misc4labor_0, name='load_misc4labor_0'),

    path('<int:bidid>/contract/', views.contract, name='contract'),
    path('<int:bidid>/depositterms/', views.depositterms, name='depositterms'),
    path('<int:bidid>/load_depositterms/', views.load_depositterms, name='load_depositterms'),

    path('<int:bidid>/terms2/', views.terms2, name='terms2'),
    path('<int:bidid>/load_terms2/', views.load_terms2, name='load_terms2'),
    path('<int:bidid>/terms3/', views.terms3, name='terms3'),
    path('<int:bidid>/load_terms3/', views.load_terms3, name='load_terms3'),
    path('<int:bidid>/termsfinal/', views.termsfinal, name='termsfinal'),
    path('<int:bidid>/load_termsfinal/', views.load_termsfinal, name='load_termsfinal'),

    path('<int:bidid>/customdeposit/', views.customdeposit, name='customdeposit'),
    path('<int:bidid>/load_depositamount/', views.load_depositamount, name='load_depositamount'),
    path('<int:bidid>/cdp/', views.cdp, name='cdp'),
    path('<int:bidid>/load_secondamount/', views.load_secondamount, name='load_secondamount'),
    path('<int:bidid>/seconddeposit/', views.seconddeposit, name='seconddeposit'),
    path('<int:bidid>/secdp/', views.secdp, name='secdp'),
    path('<int:bidid>/load_thirdamount/', views.load_thirdamount, name='load_thirdamount'),
    path('<int:bidid>/thirddeposit/', views.thirddeposit, name='thirddeposit'),
    path('<int:bidid>/thirddp/', views.thirddp, name='thirddp'),
    path('<int:bidid>/load_finalpayment/', views.load_finalpayment, name='load_finalpayment'),
    path('<int:bidid>/finalinvoice/', views.finalinvoice, name='finalinvoice'),
    path('<int:bidid>/proposal/', views.proposal, name='proposal'),




]


